branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: IE/+CC6w9vsgeOGNxLum1AEPHex4qIcfTgqmkeC06ZBJre/hEIB0zJ9lTeCOMIsLEJ1QxvZ2GgtOHPmHBEF2831Ya7TnWjAz5vvp1bY4sYXAUl4g/P+e8T2WgTn3UTwcC1a5KrmDQEmHQU8qAEXVWFnnwpXBjpAEhh4ePAEssll2wNuO3ihp8bxZr80WHjHBnRH77FKnFdvgO2vVHep8gVBNFeJlxjzqFy2fBgwYg+uEcsSTRAhG5In2xnuraT9K2TUeX6bA8WjgGDa645yjugSbVeXG79VVR7HKdYwTmuNAlk14SApE1q36/JsF+lx3FRZH6P1Xp9uYlGzscZelvY8WT2HON2hs3eATUB05SqyaDoh31UxLTxEW+LPwKBaEpMN31nDxu+xlYWEVeHtzjDMPBLaNXygQ0vy7YmQfYru+D9hwao3TWGFe4HgOwYsGR0XP6qzia+9+e665LXiia+YklTopCjB1noNoXa19T2OP+mv9tJj+JHbyXuZTY7YIOGWhW5JF7S9QtD9AEY41ns95cPALvx4uF8hjIitcnRkA3gOcQiJyZNp1rdIxg5N9gg1j0wvQMbouRuJcviu8YC9o0AZVpVOsJ5zNzi98Gm2yffQWj82v6IYAWGa0UPAGV3Cg7DDczma8B39Gsv0qtQwv10SNLanuRBZpAjo7sDc=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
