branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: FYKVRH7PCf0JzddQG6Ik3CFg/v8lL24Et9bDDG0WVOf7RJjSUGWjyu9s6gA825WlRWexXLvQ8WawSYlIvB/cne69iWSzfJKxhbJfeDXApHTOo7gCPIHh8tADuQi3jS6VUK7dZzBrdDtVTRx4r+CIQOBk9r+d5MbCtmEhc1ePgpkdXeDQw5S+AMZNxZzMuAe+niH1MAamhjX6udsiWICpWn/ohvj69QY8j5RjNIeuuTdyW7pcgjKz4BVtRERfzsGk7oofFGJwUXCFW8UIizuiCwXHrGnG5e/3DLcgvQIX2omRFE73HEZlV7IPBiXQ+YsW4HeqVC7fLxMsKfxP7Ml3rjiZ1qQytSo2aMI+Zk/zcP+etR1XxgS8qSuouxfoKFVlachT74ElOA/L+/A/mbqW3u9EOfIZgGSBSyeRaQVE2yJkFHhryVJ8TzVNoGw4pcr1SmDVjIq4eVxs5r9iBa67zi5a7ksmUklIhJGCU35vdlze+1teYUtFSxzWecfAlEh9vU+sTmA7TvM3KiBBTpoYh82uyo4tihG6pdobDGI+iFu7L9gXzW00DQkFBkCD3/ukI86YmsrlIfhFtuj+NrRJ7JiH9Vsjm5Z95ojQ2h9DB8n8UA61zh3cLujJQBOFNsZfVpzX6KfrtBy7D4faR4oeXhWNFty70J9IEXIDIVvMNzU=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
