branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  slack:
    secure: YI0dir9kCJXrbR7B2nqS9I5H7Q0UVKPaCgYXivLgvTzL+EpZwuL4bsnrYwwRO9Ti8o87bZhXrEGXkCcU6Sr6ACD6pP1xdeXqsiFUhy1Bt8kw29KPKBAy6a3muXRr/pfN3Z5N0xpyG7caJ1k/HQDS2BR/e8onQh2Go/hAX5HKNhkwS5UF1w2xzdxGsLNNPoV9Y2Gye7zHPlf0ev/B6t+Dn1dy/GBon6ULNmi8h986NWoy6eP96W9Gy1ZX3mR1BgLcZdUnhIas0Z1BVOMuhjrVIhtniGxMo4EMdahyDiSofzTpwi9HnBd/4nE9aIa9WiA0zUMcNViz6gvxhha+G95v/bQg3iDQ0ldg7LtHDQlOyG6+gnvOlX/XWr20g+Owwst4DmuXxV9X2CNv4xxapHzda4ExXwHsn1lgurePeGRf8IYn8Ox33/UoId9s3Lh9PLbBUT4BHoQpJzaM+q9X/jI92mgETbFtUpoE5rCtXebmsWjETgZfwGbax1CKy0M68TY+PZC3sBOMJ594/Z/QwObAKPs2g5blqPCHb2keilbGqSd784FbElm0ETc4a8tmS0DRgXzbGi9qYGB9BrKOAJvaEgyIZIn9Uujkua0mXQsf4Hx1Rhy0rxReLiH0G13WLtPRnu9d+ae0+ctVLE/AAUkwQCjvgJmdH/TxDDnkiXlVITo=
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: FYKVRH7PCf0JzddQG6Ik3CFg/v8lL24Et9bDDG0WVOf7RJjSUGWjyu9s6gA825WlRWexXLvQ8WawSYlIvB/cne69iWSzfJKxhbJfeDXApHTOo7gCPIHh8tADuQi3jS6VUK7dZzBrdDtVTRx4r+CIQOBk9r+d5MbCtmEhc1ePgpkdXeDQw5S+AMZNxZzMuAe+niH1MAamhjX6udsiWICpWn/ohvj69QY8j5RjNIeuuTdyW7pcgjKz4BVtRERfzsGk7oofFGJwUXCFW8UIizuiCwXHrGnG5e/3DLcgvQIX2omRFE73HEZlV7IPBiXQ+YsW4HeqVC7fLxMsKfxP7Ml3rjiZ1qQytSo2aMI+Zk/zcP+etR1XxgS8qSuouxfoKFVlachT74ElOA/L+/A/mbqW3u9EOfIZgGSBSyeRaQVE2yJkFHhryVJ8TzVNoGw4pcr1SmDVjIq4eVxs5r9iBa67zi5a7ksmUklIhJGCU35vdlze+1teYUtFSxzWecfAlEh9vU+sTmA7TvM3KiBBTpoYh82uyo4tihG6pdobDGI+iFu7L9gXzW00DQkFBkCD3/ukI86YmsrlIfhFtuj+NrRJ7JiH9Vsjm5Z95ojQ2h9DB8n8UA61zh3cLujJQBOFNsZfVpzX6KfrtBy7D4faR4oeXhWNFty70J9IEXIDIVvMNzU=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
